version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      -"80:80"
    volumes:
      -./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - seno-blackdragon-api
    networks:
      - app-network
  seno-blackdragon-api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: seno-blackdragon-api:v1.0
    container_name: seno-blackdragon-api
    hostname: seno-blackdragon-api
    env_file:
      - .env
    ports:
      - "8080:8000"
    networks:
      - app-network
   db:
    image: postgres:16
    container_name: seno-blackdragon-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: seno-blackdragon-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge