version: "3.8"

services:
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - seno-blackdragon-api
    networks: 
      - app-network
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
  db:
    image: postgres:16.4-alpine
    container_name: seno-blackdragon-db
    restart: unless-stopped
    env_file: 
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: 
      - app-network
  redis:
    image: redis:7.2-alpine
    container_name: seno-blackdragon-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: >
      redis-server
      --save 60 1
      --appendonly yes
      --loglevel warning
      --protected-mode no
    networks: 
      - app-network
  seno-blackdragon-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: seno-blackdragon-api:1.0.0
    container_name: seno-blackdragon-api
    env_file: 
      - .env
    ports:
      - "8080:8000"
    networks:
      - app-network
volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge