services:
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      seno-blackdragon-api:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:16.4-alpine
    container_name: seno-blackdragon-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    # Khuyến nghị: không publish port DB ra host trừ khi thật sự cần
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 6

  redis:
    image: redis:7.2-alpine
    container_name: seno-blackdragon-redis
    restart: unless-stopped
    # Khuyến nghị: không publish port Redis ra host trừ khi thật sự cần
    # ports:
    #   - "6379:6379"
    volumes:
      - redis_data:/data
    command: >
      redis-server
      --save 60 1
      --appendonly yes
      --loglevel warning
      --protected-mode no
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 6

  seno-blackdragon-api:
    build:
      context: .
      dockerfile: Dockerfile
    # Ép Compose build local thay vì pull
    pull_policy: build
    container_name: seno-blackdragon-api
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      # Sửa đường dẫn /healthz theo app của bạn
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/ping"]
      interval: 10s
      timeout: 3s
      retries: 10

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge
